In [67]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn import metrics

In [68]:
le=preprocessing.LabelEncoder()
targetEncoder=preprocessing.LabelEncoder()
clf = GaussianNB()
data=pd.read_csv('drug200.csv')

In [69]:
features=[feat for feat in data]
targetLabel=features[-1]
features.remove(features[-1])
features

['Age', 'Sex', 'BP', 'Cholesterol', 'Na_to_K']

In [70]:
features.remove('Na_to_K')
features.remove('Age')

In [71]:
features

['Sex', 'BP', 'Cholesterol']

In [72]:
diff_values=[]
for f in features:
    for v in data[f]:
        if v not in diff_values:
            diff_values.append(v)

diff_values

['F', 'M', 'HIGH', 'LOW', 'NORMAL']

In [73]:
dataArray=np.array(data.iloc[:,0:-2])
dataArray

array([[23, 'F', 'HIGH', 'HIGH'],
       [47, 'M', 'LOW', 'HIGH'],
       [47, 'M', 'LOW', 'HIGH'],
       [28, 'F', 'NORMAL', 'HIGH'],
       [61, 'F', 'LOW', 'HIGH'],
       [22, 'F', 'NORMAL', 'HIGH'],
       [49, 'F', 'NORMAL', 'HIGH'],
       [41, 'M', 'LOW', 'HIGH'],
       [60, 'M', 'NORMAL', 'HIGH'],
       [43, 'M', 'LOW', 'NORMAL'],
       [47, 'F', 'LOW', 'HIGH'],
       [34, 'F', 'HIGH', 'NORMAL'],
       [43, 'M', 'LOW', 'HIGH'],
       [74, 'F', 'LOW', 'HIGH'],
       [50, 'F', 'NORMAL', 'HIGH'],
       [16, 'F', 'HIGH', 'NORMAL'],
       [69, 'M', 'LOW', 'NORMAL'],
       [43, 'M', 'HIGH', 'HIGH'],
       [23, 'M', 'LOW', 'HIGH'],
       [32, 'F', 'HIGH', 'NORMAL'],
       [57, 'M', 'LOW', 'NORMAL'],
       [63, 'M', 'NORMAL', 'HIGH'],
       [47, 'M', 'LOW', 'NORMAL'],
       [48, 'F', 'LOW', 'HIGH'],
       [33, 'F', 'LOW', 'HIGH'],
       [28, 'F', 'HIGH', 'NORMAL'],
       [31, 'M', 'HIGH', 'HIGH'],
       [49, 'F', 'NORMAL', 'NORMAL'],
       [39, 'F', 'LOW', 'NORMA

In [74]:
le.fit(diff_values)
listOfValues=list(le.classes_)
listOfValues

['F', 'HIGH', 'LOW', 'M', 'NORMAL']

In [75]:
trans=[]
for d in dataArray:
    inter=[]
    for a in d:
        if a in listOfValues:
            dummy=[]
            dummy.append(a)
            inter.append(le.transform(dummy)[0])
        else:
            inter.append(a)
    trans.append(inter)
trans

[[23, 0, 1, 1],
 [47, 3, 2, 1],
 [47, 3, 2, 1],
 [28, 0, 4, 1],
 [61, 0, 2, 1],
 [22, 0, 4, 1],
 [49, 0, 4, 1],
 [41, 3, 2, 1],
 [60, 3, 4, 1],
 [43, 3, 2, 4],
 [47, 0, 2, 1],
 [34, 0, 1, 4],
 [43, 3, 2, 1],
 [74, 0, 2, 1],
 [50, 0, 4, 1],
 [16, 0, 1, 4],
 [69, 3, 2, 4],
 [43, 3, 1, 1],
 [23, 3, 2, 1],
 [32, 0, 1, 4],
 [57, 3, 2, 4],
 [63, 3, 4, 1],
 [47, 3, 2, 4],
 [48, 0, 2, 1],
 [33, 0, 2, 1],
 [28, 0, 1, 4],
 [31, 3, 1, 1],
 [49, 0, 4, 4],
 [39, 0, 2, 4],
 [45, 3, 2, 1],
 [18, 0, 4, 4],
 [74, 3, 1, 1],
 [49, 3, 2, 4],
 [65, 0, 1, 4],
 [53, 3, 4, 1],
 [46, 3, 4, 4],
 [32, 3, 1, 4],
 [39, 3, 2, 4],
 [39, 0, 4, 4],
 [15, 3, 4, 1],
 [73, 0, 4, 1],
 [58, 0, 1, 4],
 [50, 3, 4, 4],
 [23, 3, 4, 1],
 [50, 0, 4, 4],
 [66, 0, 4, 4],
 [37, 0, 1, 1],
 [68, 3, 2, 1],
 [23, 3, 4, 1],
 [28, 0, 2, 1],
 [58, 0, 1, 1],
 [67, 3, 4, 4],
 [62, 3, 2, 4],
 [24, 0, 1, 4],
 [68, 0, 1, 4],
 [26, 0, 2, 1],
 [65, 3, 1, 4],
 [40, 3, 1, 1],
 [60, 3, 4, 4],
 [34, 3, 1, 1],
 [38, 0, 2, 4],
 [24, 3, 1, 4],
 [67, 3,

In [76]:
trans=np.array(trans)
trans.shape[0]
int(trans.shape[0]/3)
trans_train=trans[0:2*int(trans.shape[0]/3)]
trans_test=trans[2*int(trans.shape[0]/3):]
print(trans_train[0],trans_test[0])

[23  0  1  1] [49  3  2  4]


In [77]:
target=data[targetLabel]
target

0      DrugY
1      drugC
2      drugC
3      drugX
4      DrugY
       ...  
195    drugC
196    drugC
197    drugX
198    drugX
199    drugX
Name: Drug, Length: 200, dtype: object

In [78]:
target=np.array(target)
target

array(['DrugY', 'drugC', 'drugC', 'drugX', 'DrugY', 'drugX', 'DrugY',
       'drugC', 'DrugY', 'DrugY', 'drugC', 'DrugY', 'DrugY', 'DrugY',
       'drugX', 'DrugY', 'drugX', 'drugA', 'drugC', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX',
       'DrugY', 'DrugY', 'drugX', 'drugB', 'drugX', 'DrugY', 'drugX',
       'drugX', 'drugA', 'drugX', 'drugX', 'drugX', 'DrugY', 'drugB',
       'DrugY', 'drugX', 'drugX', 'drugX', 'drugA', 'drugC', 'DrugY',
       'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugB', 'drugC',
       'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugA', 'DrugY',
       'drugX', 'drugB', 'DrugY', 'drugA', 'drugX', 'DrugY', 'DrugY',
       'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugA',
       'DrugY', 'drugA', 'drugX', 'drugB', 'drugX', 'drugC', 'drugA',
       'drugC', 'drugB', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY',
       'DrugY', 'Dru

In [79]:
target_values=[]
for t in target:
    if t not in target_values:
        target_values.append(t)
target_values

['DrugY', 'drugC', 'drugX', 'drugA', 'drugB']

In [80]:
targetEncoder.fit(target_values)
list(targetEncoder.classes_)

['DrugY', 'drugA', 'drugB', 'drugC', 'drugX']

In [81]:
trans_target=targetEncoder.transform(target)
trans_target
target_train=trans_target[0:2*int(trans.shape[0]/3)]
target_test=trans_target[2*int(trans.shape[0]/3):]
target_train.shape

(132,)

In [82]:
clf.fit(trans_train,target_train)

GaussianNB()

In [83]:
predicting=[40, 0, 2, 4]
pre_array=np.reshape(predicting,(1,4))
pre_array

array([[40,  0,  2,  4]])

In [84]:
ans=clf.predict(pre_array)
prob=clf.predict_proba(pre_array)
print(prob)
targetEncoder.inverse_transform(ans)

[[0.82255272 0.         0.         0.         0.17744728]]


array(['DrugY'], dtype='<U5')

In [85]:
clf.score(trans_test,target_test)

0.5441176470588235